import { projectSchema, type Project } from "./types";

export const projects: Project[] = [
  {
    slug: "ai-knowledge-rag",
    name: "AI Knowledge RAG",
    type: "personal",
    summary:
      "A production-oriented, deterministic RAG application (not multi-agent) focused on document ingestion, retrieval, grounding, and evaluation, with mandatory citations and refusal behavior when context is insufficient.",
    stack: [
      "Python",
      "FastAPI",
      "PostgreSQL",
      "pgvector",
      "SQLAlchemy (async)",
      "Alembic",
      "OpenAI",
      "pytest",
      "Next.js",
      "TypeScript",
      "Tailwind v4",
      "Vitest",
      "Docker Compose",
    ],
    featured: true,
    order: 1,
  },
  {
    slug: "coderhouse",
    name: "Coderhouse — Core Platform / Internal Modules",
    type: "professional",
    summary:
      "Professional work on a production platform involving a TypeScript microservices monorepo, backend modules, frontend applications, CI/CD, authentication, RBAC, and AWS infrastructure.",
    stack: [
      "TypeScript",
      "NestJS",
      "Nx",
      "Prisma",
      "PostgreSQL",
      "Valkey/Redis",
      "Next.js 15",
      "React",
      "Docker",
      "Terraform",
      "AWS",
    ],
    featured: true,
    order: 2,
    roleTitle: "Senior Fullstack Engineer",
    employmentDates: "Apr 2025 – Present",
  },
  {
    slug: "monchis",
    name: "Monchis — Delivery Backend",
    type: "professional",
    summary:
      "Backend work on a delivery platform involving RESTful APIs, AWS serverless infrastructure, payment integrations, purchase/cancellation flows, caching, and performance optimization.",
    stack: [
      "Node.js",
      "ReactJS",
      "MongoDB",
      "PostgreSQL",
      "AWS Lambda",
      "API Gateway",
      "AWS S3",
      "Redis",
      "GitHub",
      "Jira",
    ],
    featured: true,
    order: 3,
    roleTitle: "Backend Developer",
    employmentDates: "Jun 2023 – Apr 2025",
  },
].map((project) => projectSchema.parse(project));
